services:
  database:
    build: ./database
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./api
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/blogdb
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    working_dir: /api
  
  web:
    build: ./web
    ports:
      - "8001:8001"
    volumes:
      - ./web/app/templates:/web/app/templates
      - ./web/app/static:/web/app/static
    working_dir: /web/app
  
volumes:
  pgdata: